baseURL = 'https://site-tms--draft.pages.dev/'
languageCode = 'en-us'
title = 'Tell Me Something'
theme = 'amp'
pluralizeListTitles = false



# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "AMP"
license = "Apache v2"
licenselink = "https://github.com/pdevty/amp/blob/master/LICENSE.md"
description = "AMP (Accelerated Mobile Pages) Material Design theme"
homepage = "https://github.com/pdevty/amp/"
tags = ["blog", "portfolio", "AMP", "Material Design"]
features = ["AMP","Material Design","Google Analytics","Menu","Tags","Categories","Social links"]
min_version = 0.20
cleanDestinationDir = true

[author]
  name = "pdevty"
  homepage = "http://pdevty.github.io"


[[menu.main]]
  name = "Web Stories"
  weight = 100
  hasChildren = true
  identifier = "stories"

[[menu.main]]
name = "What are Web Stories?"
parent = "stories"
url = "/post/whatarewebstories"

[[menu.main]]
name = "Key Differences"
parent = "stories"
url = "/post/differences"


[[menu.main]]
  name = "Video"
  url = "/about"

[[menu.main]]
  name = "Audio"
  url = "/about"